// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfP06mrSTtzSoe5p_86GDZ7YUtHO00gqY',
    appId: '1:304636276243:web:59266a104d404bef6c19e6',
    messagingSenderId: '304636276243',
    projectId: 'clean-tiktok',
    authDomain: 'clean-tiktok.firebaseapp.com',
    storageBucket: 'clean-tiktok.appspot.com',
    measurementId: 'G-758KWFMEVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK1lq_urrxNSRac8C_R6rC21a-TyBPqis',
    appId: '1:304636276243:android:6674c1e5718db5d96c19e6',
    messagingSenderId: '304636276243',
    projectId: 'clean-tiktok',
    storageBucket: 'clean-tiktok.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU6Srsrkn4jovNOe9CmSOtn2WlFIFPlV8',
    appId: '1:304636276243:ios:c3a4dbc1ff46729e6c19e6',
    messagingSenderId: '304636276243',
    projectId: 'clean-tiktok',
    storageBucket: 'clean-tiktok.appspot.com',
    iosClientId: '304636276243-h6bli4n2dlp1cthafp8728s3nkp71cd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU6Srsrkn4jovNOe9CmSOtn2WlFIFPlV8',
    appId: '1:304636276243:ios:c3a4dbc1ff46729e6c19e6',
    messagingSenderId: '304636276243',
    projectId: 'clean-tiktok',
    storageBucket: 'clean-tiktok.appspot.com',
    iosClientId: '304636276243-h6bli4n2dlp1cthafp8728s3nkp71cd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
