import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/video.dart';
import '../models/data.dart';

class ApiService {
    final String channel;
    ApiService({required this.channel});
   Future<List<Video>> fetchVideos() async {
    const String apiUrl = 'https://tiktok-video-no-watermark2.p.rapidapi.com/user/posts';
    const String apiKey = 'bea33a1b7dmsh60b0fb4cf251173p136080jsn22179bcf65f0';
    const String apiHost = 'tiktok-video-no-watermark2.p.rapidapi.com';

    final Map<String, String> headers = {
      'X-RapidAPI-Key': apiKey,
      'X-RapidAPI-Host': apiHost,
    };

    final Map<String, String> params = {
      'unique_id': channel,
      'count': '1',
      'cursor': '0',
    };

    final Uri uri = Uri.parse(apiUrl).replace(queryParameters: params);

    final http.Response response = await http.get(uri, headers: headers);

    if (response.statusCode == 200) {
      final dynamic responseData = json.decode(response.body);

      Autogenerated apiResponse = Autogenerated.fromJson(responseData);

      List<dynamic>? videosData = apiResponse.data?.videos;

      if (videosData != null) {
        List<Video> videoList = videosData.map((data) => Video.fromJson(data.toJson())).toList();
        return videoList;
      } else {
        throw Exception('Failed to parse video data');
      }
    } else {
      throw Exception('Failed to fetch videos from API');
    }
  }
}

